// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbCargo
{
    public int CargId { get; set; }

    public string CargDescripcion { get; set; }

    public bool? CargEstado { get; set; }

    public int UsuaCreacion { get; set; }

    public DateTime CargFechaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public DateTime? CargFechaModificacion { get; set; }

    public virtual ICollection<TbPlaza> TbPlazas { get; set; } = new List<TbPlaza>();

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}