// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbDepartamento
{
    public string DepaCodigo { get; set; }

    public string DepaDescripcion { get; set; }

    public DateTime? DepaFechaCreacion { get; set; }

    public DateTime? DepaFechaModificacion { get; set; }

    public int? UsuaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public virtual ICollection<TbMunicipio> TbMunicipios { get; set; } = new List<TbMunicipio>();

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}