// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbEstadosCivile
{
    public int EsCiId { get; set; }

    public string EsCiDescripcion { get; set; }

    public DateTime EsCiFechaCreacion { get; set; }

    public DateTime? EsCiFechaModificacion { get; set; }

    public int UsuaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public virtual ICollection<TbPersona> TbPersonas { get; set; } = new List<TbPersona>();

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}