// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbGuardado
{
    public int GuarId { get; set; }

    public int PlazId { get; set; }

    public int UsuaId { get; set; }

    public bool? GuarEstado { get; set; }

    public int UsuaCreacion { get; set; }

    public DateTime GuarFechaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public DateTime? GuarFechaModificacion { get; set; }

    public virtual TbPlaza Plaz { get; set; }

    public virtual TbUsuario Usua { get; set; }

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}