// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbMunicipio
{
    public string MuniCodigo { get; set; }

    public string MuniDescripcion { get; set; }

    public string DepaCodigo { get; set; }

    public DateTime? MuniFechaCreacion { get; set; }

    public DateTime? MuniFechaModificacion { get; set; }

    public int? UsuaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public virtual TbDepartamento DepaCodigoNavigation { get; set; }

    public virtual ICollection<TbPersona> TbPersonas { get; set; } = new List<TbPersona>();

    public virtual ICollection<TbPlaza> TbPlazas { get; set; } = new List<TbPlaza>();

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}