// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbPantalla
{
    public int PantId { get; set; }

    public string PantNombre { get; set; }

    public string PantRuta { get; set; }

    public string PantControlador { get; set; }

    public string PantEsquema { get; set; }

    public int? UsuaCreacion { get; set; }

    public DateTime? PantFechaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public DateTime? PantFechaModificacion { get; set; }

    public virtual ICollection<TbPantallasPorRol> TbPantallasPorRols { get; set; } = new List<TbPantallasPorRol>();

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}