// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class tbPantallas
{
    public int Pant_Id { get; set; }

    public string Pant_Nombre { get; set; }

    public string Pant_Ruta { get; set; }

    public string Pant_Controlador { get; set; }

    public string Pant_Esquema { get; set; }

    public int? Usua_Creacion { get; set; }

    public DateTime? Pant_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Pant_FechaModificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbPantallasPorRol> tbPantallasPorRol { get; set; } = new List<tbPantallasPorRol>();
}