// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbPantallasPorRol
{
    public int PaRoId { get; set; }

    public int? PantId { get; set; }

    public int? RoleId { get; set; }

    public int? UsuaCreacion { get; set; }

    public DateTime? PaRoFechaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public DateTime? PaRoFechaModificacion { get; set; }

    public virtual TbPantalla Pant { get; set; }

    public virtual TbRole Role { get; set; }

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}