// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class tbPantallasPorRol
{
    public int PaRo_Id { get; set; }

    public int? Pant_Id { get; set; }

    public int? Role_Id { get; set; }

    public int? Usua_Creacion { get; set; }

    public DateTime? PaRo_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? PaRo_FechaModificacion { get; set; }


}