// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbPersona
{
    public int PersId { get; set; }

    public string PersDni { get; set; }

    public string PersNombres { get; set; }

    public string PersApellidos { get; set; }

    public string PersTelefono { get; set; }

    public string PersSexo { get; set; }

    public string PersDireccion { get; set; }

    public string PersCurriculum { get; set; }

    public int EsCiId { get; set; }

    public string MuniCodigo { get; set; }

    public bool? PersEstado { get; set; }

    public int UsuaCreacion { get; set; }

    public DateTime PersFechaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public DateTime? PersFechaModificacion { get; set; }

    public virtual TbEstadosCivile EsCi { get; set; }

    public virtual TbMunicipio MuniCodigoNavigation { get; set; }

    public virtual ICollection<TbUsuario> TbUsuarios { get; set; } = new List<TbUsuario>();

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}