// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class tbPersonas
{
    public int Pers_Id { get; set; }

    public string Pers_DNI { get; set; }

    public string Pers_Nombres { get; set; }

    public string Pers_Apellidos { get; set; }

    public string Pers_Telefono { get; set; }

    public string Pers_Sexo { get; set; }

    public string Pers_Direccion { get; set; }

    public string Pers_Curriculum { get; set; }

    public int EsCi_Id { get; set; }

    public string Muni_Codigo { get; set; }

    public bool? Pers_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Pers_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Pers_FechaModificacion { get; set; }

    public virtual tbEstadosCiviles EsCi { get; set; }

    public virtual tbMunicipios Muni_CodigoNavigation { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbUsuarios> tbUsuarios { get; set; } = new List<tbUsuarios>();
}