// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class tbPlazas
{
    public int Plaz_Id { get; set; }

    public string Plaz_Descripcion { get; set; }

    public string Plaz_Informacion { get; set; }

    public string Plaz_Direccion { get; set; }

    public string Plaz_Telefono { get; set; }

    public string Plaz_Correo { get; set; }

    public string Plaz_Imagen { get; set; }

    public string Muni_Codigo { get; set; }

    public int Cate_Id { get; set; }

    public int Usua_Id { get; set; }

    public int Carg_Id { get; set; }

    public int TiCo_Id { get; set; }

    public bool? Plaz_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Plaz_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Plaz_FechaModificacion { get; set; }

    public virtual tbCargos Carg { get; set; }

    public virtual tbCategorias Cate { get; set; }

    public virtual tbMunicipios Muni_CodigoNavigation { get; set; }

    public virtual tbTiposContrato TiCo { get; set; }

    public virtual tbUsuarios Usua { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbGuardados> tbGuardados { get; set; } = new List<tbGuardados>();

    public virtual ICollection<tbSolicitudes> tbSolicitudes { get; set; } = new List<tbSolicitudes>();
}