// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbPlaza
{
    public int PlazId { get; set; }

    public string PlazDescripcion { get; set; }

    public string PlazInformacion { get; set; }

    public string PlazDireccion { get; set; }

    public string PlazTelefono { get; set; }

    public string PlazCorreo { get; set; }

    public string PlazImagen { get; set; }

    public string MuniCodigo { get; set; }

    public int CateId { get; set; }

    public int UsuaId { get; set; }

    public int CargId { get; set; }

    public int TiCoId { get; set; }

    public bool? PlazEstado { get; set; }

    public int UsuaCreacion { get; set; }

    public DateTime PlazFechaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public DateTime? PlazFechaModificacion { get; set; }

    public virtual TbCargo Carg { get; set; }

    public virtual TbCategoria Cate { get; set; }

    public virtual TbMunicipio MuniCodigoNavigation { get; set; }

    public virtual ICollection<TbGuardado> TbGuardados { get; set; } = new List<TbGuardado>();

    public virtual ICollection<TbSolicitude> TbSolicitudes { get; set; } = new List<TbSolicitude>();

    public virtual TbTiposContrato TiCo { get; set; }

    public virtual TbUsuario Usua { get; set; }

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}