// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbRequisito
{
    public int RequId { get; set; }

    public string RequDescripcion { get; set; }

    public string RequInformacion { get; set; }

    public bool? RequEstado { get; set; }

    public int UsuaCreacion { get; set; }

    public DateTime RequFechaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public DateTime? RequFechaModificacion { get; set; }

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}