// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbRole
{
    public int RoleId { get; set; }

    public string RoleDescripcion { get; set; }

    public bool RoleEstado { get; set; }

    public DateTime? RoleFechaCreacion { get; set; }

    public DateTime? RoleFechaModificacion { get; set; }

    public int? UsuaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public virtual ICollection<TbPantallasPorRol> TbPantallasPorRols { get; set; } = new List<TbPantallasPorRol>();

    public virtual ICollection<TbUsuario> TbUsuarios { get; set; } = new List<TbUsuario>();

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}