// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class tbRoles
{
    public int Role_Id { get; set; }

    public string Role_Descripcion { get; set; }

    public bool Role_Estado { get; set; }

    public DateTime? Role_FechaCreacion { get; set; }

    public DateTime? Role_FechaModificacion { get; set; }

    public int? Usua_Creacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbPantallasPorRol> tbPantallasPorRol { get; set; } = new List<tbPantallasPorRol>();

    public virtual ICollection<tbUsuarios> tbUsuarios { get; set; } = new List<tbUsuarios>();
}