// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class tbSolicitudes
{
    public int Soli_Id { get; set; }

    public string Soli_Comentario { get; set; }

    public string Soli_Revision { get; set; }

    public int Plaz_Id { get; set; }

    public int Usua_Id { get; set; }

    public bool? Soli_Estado { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Soli_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Soli_FechaModificacion { get; set; }

    public virtual tbPlazas Plaz { get; set; }

    public virtual tbUsuarios Usua { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}