// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbTiposContrato
{
    public int TiCoId { get; set; }

    public string TiCoDescripcion { get; set; }

    public bool? TiCoEstado { get; set; }

    public int UsuaCreacion { get; set; }

    public DateTime TiCoFechaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public DateTime? TiCoFechaModificacion { get; set; }

    public virtual ICollection<TbPlaza> TbPlazas { get; set; } = new List<TbPlaza>();

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}