// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Jobster.Entities.Entities;

public partial class TbUsuario
{
    public int UsuaId { get; set; }

    public string UsuaNombre { get; set; }

    public string UsuaContrasena { get; set; }

    public string UsuaCorreo { get; set; }

    public bool UsuaEsAdmin { get; set; }

    public bool UsuaPublicador { get; set; }

    public string UsuaImagen { get; set; }

    public int PersId { get; set; }

    public int RoleId { get; set; }

    public int UsuaCreacion { get; set; }

    public DateTime UsuaFechaCreacion { get; set; }

    public int? UsuaModificacion { get; set; }

    public DateTime? UsuaFechaModificacion { get; set; }

    public bool? UsuaEstado { get; set; }

    public virtual ICollection<TbUsuario> InverseUsuaCreacionNavigation { get; set; } = new List<TbUsuario>();

    public virtual ICollection<TbUsuario> InverseUsuaModificacionNavigation { get; set; } = new List<TbUsuario>();

    public virtual TbPersona Pers { get; set; }

    public virtual TbRole Role { get; set; }

    public virtual ICollection<TbCargo> TbCargoUsuaCreacionNavigations { get; set; } = new List<TbCargo>();

    public virtual ICollection<TbCargo> TbCargoUsuaModificacionNavigations { get; set; } = new List<TbCargo>();

    public virtual ICollection<TbCategoria> TbCategoriaUsuaCreacionNavigations { get; set; } = new List<TbCategoria>();

    public virtual ICollection<TbCategoria> TbCategoriaUsuaModificacionNavigations { get; set; } = new List<TbCategoria>();

    public virtual ICollection<TbDepartamento> TbDepartamentoUsuaCreacionNavigations { get; set; } = new List<TbDepartamento>();

    public virtual ICollection<TbDepartamento> TbDepartamentoUsuaModificacionNavigations { get; set; } = new List<TbDepartamento>();

    public virtual ICollection<TbEstadosCivile> TbEstadosCivileUsuaCreacionNavigations { get; set; } = new List<TbEstadosCivile>();

    public virtual ICollection<TbEstadosCivile> TbEstadosCivileUsuaModificacionNavigations { get; set; } = new List<TbEstadosCivile>();

    public virtual ICollection<TbGuardado> TbGuardadoUsuaCreacionNavigations { get; set; } = new List<TbGuardado>();

    public virtual ICollection<TbGuardado> TbGuardadoUsuaModificacionNavigations { get; set; } = new List<TbGuardado>();

    public virtual ICollection<TbGuardado> TbGuardadoUsuas { get; set; } = new List<TbGuardado>();

    public virtual ICollection<TbMunicipio> TbMunicipioUsuaCreacionNavigations { get; set; } = new List<TbMunicipio>();

    public virtual ICollection<TbMunicipio> TbMunicipioUsuaModificacionNavigations { get; set; } = new List<TbMunicipio>();

    public virtual ICollection<TbPantalla> TbPantallaUsuaCreacionNavigations { get; set; } = new List<TbPantalla>();

    public virtual ICollection<TbPantalla> TbPantallaUsuaModificacionNavigations { get; set; } = new List<TbPantalla>();

    public virtual ICollection<TbPantallasPorRol> TbPantallasPorRolUsuaCreacionNavigations { get; set; } = new List<TbPantallasPorRol>();

    public virtual ICollection<TbPantallasPorRol> TbPantallasPorRolUsuaModificacionNavigations { get; set; } = new List<TbPantallasPorRol>();

    public virtual ICollection<TbPersona> TbPersonaUsuaCreacionNavigations { get; set; } = new List<TbPersona>();

    public virtual ICollection<TbPersona> TbPersonaUsuaModificacionNavigations { get; set; } = new List<TbPersona>();

    public virtual ICollection<TbPlaza> TbPlazaUsuaCreacionNavigations { get; set; } = new List<TbPlaza>();

    public virtual ICollection<TbPlaza> TbPlazaUsuaModificacionNavigations { get; set; } = new List<TbPlaza>();

    public virtual ICollection<TbPlaza> TbPlazaUsuas { get; set; } = new List<TbPlaza>();

    public virtual ICollection<TbRequisito> TbRequisitoUsuaCreacionNavigations { get; set; } = new List<TbRequisito>();

    public virtual ICollection<TbRequisito> TbRequisitoUsuaModificacionNavigations { get; set; } = new List<TbRequisito>();

    public virtual ICollection<TbRole> TbRoleUsuaCreacionNavigations { get; set; } = new List<TbRole>();

    public virtual ICollection<TbRole> TbRoleUsuaModificacionNavigations { get; set; } = new List<TbRole>();

    public virtual ICollection<TbSolicitude> TbSolicitudeUsuaCreacionNavigations { get; set; } = new List<TbSolicitude>();

    public virtual ICollection<TbSolicitude> TbSolicitudeUsuaModificacionNavigations { get; set; } = new List<TbSolicitude>();

    public virtual ICollection<TbSolicitude> TbSolicitudeUsuas { get; set; } = new List<TbSolicitude>();

    public virtual ICollection<TbTiposContrato> TbTiposContratoUsuaCreacionNavigations { get; set; } = new List<TbTiposContrato>();

    public virtual ICollection<TbTiposContrato> TbTiposContratoUsuaModificacionNavigations { get; set; } = new List<TbTiposContrato>();

    public virtual TbUsuario UsuaCreacionNavigation { get; set; }

    public virtual TbUsuario UsuaModificacionNavigation { get; set; }
}