// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sistema_Jobster.Entities.Entities;

public partial class tbUsuarios
{
    public int Usua_Id { get; set; }

    public string Usua_Nombre { get; set; }

    public string Usua_Contrasena { get; set; }

    public string Usua_Correo { get; set; }

    public bool Usua_EsAdmin { get; set; }

    public bool Usua_Publicador { get; set; }

    public string Usua_Imagen { get; set; }

    public int Pers_Id { get; set; }

    public int Role_Id { get; set; }

    [NotMapped]
    public string pers_Nombres { get; set; }

    [NotMapped]
    public string pers_Apellidos { get; set; }

    [NotMapped]
    public string role_Descripcion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Usua_FechaCreacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Usua_FechaModificacion { get; set; }

    public bool? Usua_Estado { get; set; }

 

    public virtual ICollection<tbUsuarios> InverseUsua_CreacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual ICollection<tbUsuarios> InverseUsua_ModificacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual tbPersonas Pers { get; set; }

    public virtual tbRoles Role { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbCargos> tbCargosUsua_CreacionNavigation { get; set; } = new List<tbCargos>();

    public virtual ICollection<tbCargos> tbCargosUsua_ModificacionNavigation { get; set; } = new List<tbCargos>();

    public virtual ICollection<tbCategorias> tbCategoriasUsua_CreacionNavigation { get; set; } = new List<tbCategorias>();

    public virtual ICollection<tbCategorias> tbCategoriasUsua_ModificacionNavigation { get; set; } = new List<tbCategorias>();

    public virtual ICollection<tbDepartamentos> tbDepartamentosUsua_CreacionNavigation { get; set; } = new List<tbDepartamentos>();

    public virtual ICollection<tbDepartamentos> tbDepartamentosUsua_ModificacionNavigation { get; set; } = new List<tbDepartamentos>();

    public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesUsua_CreacionNavigation { get; set; } = new List<tbEstadosCiviles>();

    public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesUsua_ModificacionNavigation { get; set; } = new List<tbEstadosCiviles>();

    public virtual ICollection<tbGuardados> tbGuardadosUsua { get; set; } = new List<tbGuardados>();

    public virtual ICollection<tbGuardados> tbGuardadosUsua_CreacionNavigation { get; set; } = new List<tbGuardados>();

    public virtual ICollection<tbGuardados> tbGuardadosUsua_ModificacionNavigation { get; set; } = new List<tbGuardados>();

    public virtual ICollection<tbMunicipios> tbMunicipiosUsua_CreacionNavigation { get; set; } = new List<tbMunicipios>();

    public virtual ICollection<tbMunicipios> tbMunicipiosUsua_ModificacionNavigation { get; set; } = new List<tbMunicipios>();

    public virtual ICollection<tbPantallasPorRol> tbPantallasPorRolUsua_CreacionNavigation { get; set; } = new List<tbPantallasPorRol>();

    public virtual ICollection<tbPantallasPorRol> tbPantallasPorRolUsua_ModificacionNavigation { get; set; } = new List<tbPantallasPorRol>();

    public virtual ICollection<tbPantallas> tbPantallasUsua_CreacionNavigation { get; set; } = new List<tbPantallas>();

    public virtual ICollection<tbPantallas> tbPantallasUsua_ModificacionNavigation { get; set; } = new List<tbPantallas>();

    public virtual ICollection<tbPersonas> tbPersonasUsua_CreacionNavigation { get; set; } = new List<tbPersonas>();

    public virtual ICollection<tbPersonas> tbPersonasUsua_ModificacionNavigation { get; set; } = new List<tbPersonas>();

    public virtual ICollection<tbPlazas> tbPlazasUsua { get; set; } = new List<tbPlazas>();

    public virtual ICollection<tbPlazas> tbPlazasUsua_CreacionNavigation { get; set; } = new List<tbPlazas>();

    public virtual ICollection<tbPlazas> tbPlazasUsua_ModificacionNavigation { get; set; } = new List<tbPlazas>();

    public virtual ICollection<tbRequisitos> tbRequisitosUsua_CreacionNavigation { get; set; } = new List<tbRequisitos>();

    public virtual ICollection<tbRequisitos> tbRequisitosUsua_ModificacionNavigation { get; set; } = new List<tbRequisitos>();

    public virtual ICollection<tbRoles> tbRolesUsua_CreacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbRoles> tbRolesUsua_ModificacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbSolicitudes> tbSolicitudesUsua { get; set; } = new List<tbSolicitudes>();

    public virtual ICollection<tbSolicitudes> tbSolicitudesUsua_CreacionNavigation { get; set; } = new List<tbSolicitudes>();

    public virtual ICollection<tbSolicitudes> tbSolicitudesUsua_ModificacionNavigation { get; set; } = new List<tbSolicitudes>();

    public virtual ICollection<tbTiposContrato> tbTiposContratoUsua_CreacionNavigation { get; set; } = new List<tbTiposContrato>();

    public virtual ICollection<tbTiposContrato> tbTiposContratoUsua_ModificacionNavigation { get; set; } = new List<tbTiposContrato>();
 

}