// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Sistema_Jobster.Entities.Entities;

namespace Sistema_Jobster.DataAccess.Context;

public partial class db_ab9479_jobsterContext : DbContext
{
    public db_ab9479_jobsterContext(DbContextOptions<db_ab9479_jobsterContext> options)
        : base(options)
    {
    }
    public db_ab9479_jobsterContext()
    { }
    public virtual DbSet<TbCargo> TbCargos { get; set; }

    public virtual DbSet<TbCategoria> TbCategorias { get; set; }

    public virtual DbSet<TbDepartamento> TbDepartamentos { get; set; }

    public virtual DbSet<TbEstadosCivile> TbEstadosCiviles { get; set; }

    public virtual DbSet<TbGuardado> TbGuardados { get; set; }

    public virtual DbSet<TbMunicipio> TbMunicipios { get; set; }

    public virtual DbSet<TbPantalla> TbPantallas { get; set; }

    public virtual DbSet<TbPantallasPorRol> TbPantallasPorRols { get; set; }

    public virtual DbSet<TbPersona> TbPersonas { get; set; }

    public virtual DbSet<TbPlaza> TbPlazas { get; set; }

    public virtual DbSet<TbRequisito> TbRequisitos { get; set; }

    public virtual DbSet<TbRole> TbRoles { get; set; }

    public virtual DbSet<TbSolicitude> TbSolicitudes { get; set; }

    public virtual DbSet<TbTiposContrato> TbTiposContratos { get; set; }

    public virtual DbSet<TbUsuario> TbUsuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TbCargo>(entity =>
        {
            entity.HasKey(e => e.CargId).HasName("PK_Plaz_tbCargos_Carg_Id");

            entity.ToTable("tbCargos", "Plaz");

            entity.Property(e => e.CargId).HasColumnName("Carg_Id");
            entity.Property(e => e.CargDescripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Carg_Descripcion");
            entity.Property(e => e.CargEstado)
                .HasDefaultValue(true)
                .HasColumnName("Carg_Estado");
            entity.Property(e => e.CargFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Carg_FechaCreacion");
            entity.Property(e => e.CargFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Carg_FechaModificacion");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbCargoUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbCargos_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbCargoUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Plaz_tbCargos_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbCategoria>(entity =>
        {
            entity.HasKey(e => e.CateId).HasName("PK_Plaz_tbCategorias_Cate_Id");

            entity.ToTable("tbCategorias", "Plaz");

            entity.Property(e => e.CateId).HasColumnName("Cate_Id");
            entity.Property(e => e.CateDescripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Cate_Descripcion");
            entity.Property(e => e.CateEstado)
                .HasDefaultValue(true)
                .HasColumnName("Cate_Estado");
            entity.Property(e => e.CateFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Cate_FechaCreacion");
            entity.Property(e => e.CateFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Cate_FechaModificacion");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbCategoriaUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbCategorias_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbCategoriaUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Plaz_tbCategorias_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbDepartamento>(entity =>
        {
            entity.HasKey(e => e.DepaCodigo).HasName("PK_Gral_tbDepartamentos_Depa_Codigo");

            entity.ToTable("tbDepartamentos", "Gral");

            entity.Property(e => e.DepaCodigo)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("Depa_Codigo");
            entity.Property(e => e.DepaDescripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Depa_Descripcion");
            entity.Property(e => e.DepaFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Depa_FechaCreacion");
            entity.Property(e => e.DepaFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Depa_FechaModificacion");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbDepartamentoUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .HasConstraintName("FK_Gral_tbDepartamentos_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbDepartamentoUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Gral_tbDepartamentos_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbEstadosCivile>(entity =>
        {
            entity.HasKey(e => e.EsCiId).HasName("PK_Gral_tbEstadosCiviles_EsCi_Id");

            entity.ToTable("tbEstadosCiviles", "Gral");

            entity.Property(e => e.EsCiId).HasColumnName("EsCi_Id");
            entity.Property(e => e.EsCiDescripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("EsCi_Descripcion");
            entity.Property(e => e.EsCiFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("EsCi_FechaCreacion");
            entity.Property(e => e.EsCiFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("EsCi_FechaModificacion");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbEstadosCivileUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbEstadosCiviles_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbEstadosCivileUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Gral_tbEstadosCiviles_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbGuardado>(entity =>
        {
            entity.HasKey(e => e.GuarId).HasName("PK_Plaz_tbGuardados_Guar_Id");

            entity.ToTable("tbGuardados", "Plaz");

            entity.Property(e => e.GuarId).HasColumnName("Guar_Id");
            entity.Property(e => e.GuarEstado)
                .HasDefaultValue(true)
                .HasColumnName("Guar_Estado");
            entity.Property(e => e.GuarFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Guar_FechaCreacion");
            entity.Property(e => e.GuarFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Guar_FechaModificacion");
            entity.Property(e => e.PlazId).HasColumnName("Plaz_Id");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaId).HasColumnName("Usua_Id");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.Plaz).WithMany(p => p.TbGuardados)
                .HasForeignKey(d => d.PlazId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbGuardados_Plaz_tbPlazas_Plaz_Id");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbGuardadoUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbGuardados_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua).WithMany(p => p.TbGuardadoUsuas)
                .HasForeignKey(d => d.UsuaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbGuardados_Acce_tbUsuarios_Usua_Id");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbGuardadoUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Plaz_tbGuardados_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbMunicipio>(entity =>
        {
            entity.HasKey(e => e.MuniCodigo).HasName("PK_Gral_tbMunicipios_Muni_Codigo");

            entity.ToTable("tbMunicipios", "Gral");

            entity.Property(e => e.MuniCodigo)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("Muni_Codigo");
            entity.Property(e => e.DepaCodigo)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("Depa_Codigo");
            entity.Property(e => e.MuniDescripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Muni_Descripcion");
            entity.Property(e => e.MuniFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Muni_FechaCreacion");
            entity.Property(e => e.MuniFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Muni_FechaModificacion");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.DepaCodigoNavigation).WithMany(p => p.TbMunicipios)
                .HasForeignKey(d => d.DepaCodigo)
                .HasConstraintName("FK_Gral_tbMunicipios_Gral_tbDepartamentos_Depa_Codigo");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbMunicipioUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .HasConstraintName("FK_Gral_tbMunicipios_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbMunicipioUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Gral_tbMunicipios_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbPantalla>(entity =>
        {
            entity.HasKey(e => e.PantId).HasName("PK_Acce_tbPantallas_Pant_Id");

            entity.ToTable("tbPantallas", "Acce");

            entity.Property(e => e.PantId).HasColumnName("Pant_Id");
            entity.Property(e => e.PantControlador)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Pant_Controlador");
            entity.Property(e => e.PantEsquema)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("Pant_Esquema");
            entity.Property(e => e.PantFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Pant_FechaCreacion");
            entity.Property(e => e.PantFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Pant_FechaModificacion");
            entity.Property(e => e.PantNombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Pant_Nombre");
            entity.Property(e => e.PantRuta)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Pant_Ruta");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbPantallaUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .HasConstraintName("FK_Acce_tbPantallas_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbPantallaUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Acce_tbPantallas_Usua_Modificacion");
        });

        modelBuilder.Entity<TbPantallasPorRol>(entity =>
        {
            entity.HasKey(e => e.PaRoId).HasName("PK_Acce_tbPantallasPorRol");

            entity.ToTable("tbPantallasPorRol", "Acce");

            entity.Property(e => e.PaRoId).HasColumnName("PaRo_Id");
            entity.Property(e => e.PaRoFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("PaRo_FechaCreacion");
            entity.Property(e => e.PaRoFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("PaRo_FechaModificacion");
            entity.Property(e => e.PantId).HasColumnName("Pant_Id");
            entity.Property(e => e.RoleId).HasColumnName("Role_Id");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.Pant).WithMany(p => p.TbPantallasPorRols)
                .HasForeignKey(d => d.PantId)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Pant_Id");

            entity.HasOne(d => d.Role).WithMany(p => p.TbPantallasPorRols)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Role_Id");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbPantallasPorRolUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbPantallasPorRolUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Usua_Modificacion");
        });

        modelBuilder.Entity<TbPersona>(entity =>
        {
            entity.HasKey(e => e.PersId).HasName("PK_Gral_tbPersonas_Pers_Id");

            entity.ToTable("tbPersonas", "Gral");

            entity.HasIndex(e => e.PersDni, "UQ__tbPerson__CC1C0A1044A96CBE").IsUnique();

            entity.Property(e => e.PersId).HasColumnName("Pers_Id");
            entity.Property(e => e.EsCiId).HasColumnName("EsCi_Id");
            entity.Property(e => e.MuniCodigo)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("Muni_Codigo");
            entity.Property(e => e.PersApellidos)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Pers_Apellidos");
            entity.Property(e => e.PersCurriculum)
                .IsUnicode(false)
                .HasColumnName("Pers_Curriculum");
            entity.Property(e => e.PersDireccion)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("Pers_Direccion");
            entity.Property(e => e.PersDni)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Pers_DNI");
            entity.Property(e => e.PersEstado)
                .HasDefaultValue(true)
                .HasColumnName("Pers_Estado");
            entity.Property(e => e.PersFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Pers_FechaCreacion");
            entity.Property(e => e.PersFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Pers_FechaModificacion");
            entity.Property(e => e.PersNombres)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Pers_Nombres");
            entity.Property(e => e.PersSexo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("Pers_Sexo");
            entity.Property(e => e.PersTelefono)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Pers_Telefono");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.EsCi).WithMany(p => p.TbPersonas)
                .HasForeignKey(d => d.EsCiId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbPersonas_Gral_tbEstadosCiviles_EsCi_Id");

            entity.HasOne(d => d.MuniCodigoNavigation).WithMany(p => p.TbPersonas)
                .HasForeignKey(d => d.MuniCodigo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbPersonas_Gral_tbMunicipios_Muni_Codigo");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbPersonaUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbPersonas_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbPersonaUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Gral_tbPersonas_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbPlaza>(entity =>
        {
            entity.HasKey(e => e.PlazId).HasName("PK_Plaz_tbPlazas_Plaz_Id");

            entity.ToTable("tbPlazas", "Plaz");

            entity.Property(e => e.PlazId).HasColumnName("Plaz_Id");
            entity.Property(e => e.CargId).HasColumnName("Carg_Id");
            entity.Property(e => e.CateId).HasColumnName("Cate_Id");
            entity.Property(e => e.MuniCodigo)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("Muni_Codigo");
            entity.Property(e => e.PlazCorreo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Plaz_Correo");
            entity.Property(e => e.PlazDescripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Plaz_Descripcion");
            entity.Property(e => e.PlazDireccion)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("Plaz_Direccion");
            entity.Property(e => e.PlazEstado)
                .HasDefaultValue(true)
                .HasColumnName("Plaz_Estado");
            entity.Property(e => e.PlazFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Plaz_FechaCreacion");
            entity.Property(e => e.PlazFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Plaz_FechaModificacion");
            entity.Property(e => e.PlazImagen)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("Plaz_Imagen");
            entity.Property(e => e.PlazInformacion)
                .IsRequired()
                .HasMaxLength(4000)
                .IsUnicode(false)
                .HasColumnName("Plaz_Informacion");
            entity.Property(e => e.PlazTelefono)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("Plaz_Telefono");
            entity.Property(e => e.TiCoId).HasColumnName("TiCo_Id");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaId).HasColumnName("Usua_Id");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.Carg).WithMany(p => p.TbPlazas)
                .HasForeignKey(d => d.CargId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbPlazas_Plaz_tbCargos_Carg_Id");

            entity.HasOne(d => d.Cate).WithMany(p => p.TbPlazas)
                .HasForeignKey(d => d.CateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbPlazas_Plaz_tbCategorias_Cate_Id");

            entity.HasOne(d => d.MuniCodigoNavigation).WithMany(p => p.TbPlazas)
                .HasForeignKey(d => d.MuniCodigo)
                .HasConstraintName("FK_Plaz_tbPlazas_Plaz_tbMunicipios_Muni_Codigo");

            entity.HasOne(d => d.TiCo).WithMany(p => p.TbPlazas)
                .HasForeignKey(d => d.TiCoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbPlazas_Plaz_tbTiposContrato_TiCo_Id");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbPlazaUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbPlazas_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua).WithMany(p => p.TbPlazaUsuas)
                .HasForeignKey(d => d.UsuaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbPlazas_Acce_tbUsuarios_Usua_Id");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbPlazaUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Plaz_tbPlazas_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbRequisito>(entity =>
        {
            entity.HasKey(e => e.RequId).HasName("PK_Plaz_tbRequisitos_Requ_Id");

            entity.ToTable("tbRequisitos", "Plaz");

            entity.Property(e => e.RequId).HasColumnName("Requ_Id");
            entity.Property(e => e.RequDescripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Requ_Descripcion");
            entity.Property(e => e.RequEstado)
                .HasDefaultValue(true)
                .HasColumnName("Requ_Estado");
            entity.Property(e => e.RequFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Requ_FechaCreacion");
            entity.Property(e => e.RequFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Requ_FechaModificacion");
            entity.Property(e => e.RequInformacion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Requ_Informacion");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbRequisitoUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbRequisitos_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbRequisitoUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Plaz_tbRequisitos_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbRole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK_Acce_tbRoles_Role_Id");

            entity.ToTable("tbRoles", "Acce");

            entity.Property(e => e.RoleId).HasColumnName("Role_Id");
            entity.Property(e => e.RoleDescripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Role_Descripcion");
            entity.Property(e => e.RoleEstado)
                .HasDefaultValue(true)
                .HasColumnName("Role_Estado");
            entity.Property(e => e.RoleFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Role_FechaCreacion");
            entity.Property(e => e.RoleFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Role_FechaModificacion");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbRoleUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .HasConstraintName("FK_Acce_tbRoles_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbRoleUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Acce_tbRoles_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbSolicitude>(entity =>
        {
            entity.HasKey(e => e.SoliId).HasName("PK_Plaz_tbSolicitudes_Soli_Id");

            entity.ToTable("tbSolicitudes", "Plaz");

            entity.Property(e => e.SoliId).HasColumnName("Soli_Id");
            entity.Property(e => e.PlazId).HasColumnName("Plaz_Id");
            entity.Property(e => e.SoliComentario)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Soli_Comentario");
            entity.Property(e => e.SoliEstado)
                .HasDefaultValue(true)
                .HasColumnName("Soli_Estado");
            entity.Property(e => e.SoliFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Soli_FechaCreacion");
            entity.Property(e => e.SoliFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Soli_FechaModificacion");
            entity.Property(e => e.SoliRevision)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("Soli_Revision");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaId).HasColumnName("Usua_Id");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.Plaz).WithMany(p => p.TbSolicitudes)
                .HasForeignKey(d => d.PlazId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbSolicitudes_Plaz_tbSolicitudes_Plaz_Id");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbSolicitudeUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbSolicitudes_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua).WithMany(p => p.TbSolicitudeUsuas)
                .HasForeignKey(d => d.UsuaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbSolicitudes_Acce_tbUsuarios_Usua_Id");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbSolicitudeUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Plaz_tbSolicitudes_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbTiposContrato>(entity =>
        {
            entity.HasKey(e => e.TiCoId).HasName("PK_Plaz_tbTiposContrato_TiCo_Id");

            entity.ToTable("tbTiposContrato", "Plaz");

            entity.Property(e => e.TiCoId).HasColumnName("TiCo_Id");
            entity.Property(e => e.TiCoDescripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("TiCo_Descripcion");
            entity.Property(e => e.TiCoEstado)
                .HasDefaultValue(true)
                .HasColumnName("TiCo_Estado");
            entity.Property(e => e.TiCoFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("TiCo_FechaCreacion");
            entity.Property(e => e.TiCoFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("TiCo_FechaModificacion");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.TbTiposContratoUsuaCreacionNavigations)
                .HasForeignKey(d => d.UsuaCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbTiposContrato_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.TbTiposContratoUsuaModificacionNavigations)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Plaz_tbTiposContrato_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<TbUsuario>(entity =>
        {
            entity.HasKey(e => e.UsuaId).HasName("PK_Acce_tbUsuarios_Usua_Id");

            entity.ToTable("tbUsuarios", "Acce");

            entity.Property(e => e.UsuaId).HasColumnName("Usua_Id");
            entity.Property(e => e.PersId).HasColumnName("Pers_Id");
            entity.Property(e => e.RoleId).HasColumnName("Role_Id");
            entity.Property(e => e.UsuaContrasena)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("Usua_Contrasena");
            entity.Property(e => e.UsuaCorreo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Usua_Correo");
            entity.Property(e => e.UsuaCreacion).HasColumnName("Usua_Creacion");
            entity.Property(e => e.UsuaEsAdmin).HasColumnName("Usua_EsAdmin");
            entity.Property(e => e.UsuaEstado)
                .HasDefaultValue(true)
                .HasColumnName("Usua_Estado");
            entity.Property(e => e.UsuaFechaCreacion)
                .HasColumnType("datetime")
                .HasColumnName("Usua_FechaCreacion");
            entity.Property(e => e.UsuaFechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("Usua_FechaModificacion");
            entity.Property(e => e.UsuaImagen)
                .IsUnicode(false)
                .HasColumnName("Usua_Imagen");
            entity.Property(e => e.UsuaModificacion).HasColumnName("Usua_Modificacion");
            entity.Property(e => e.UsuaNombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Usua_Nombre");
            entity.Property(e => e.UsuaPublicador).HasColumnName("Usua_Publicador");

            entity.HasOne(d => d.Pers).WithMany(p => p.TbUsuarios)
                .HasForeignKey(d => d.PersId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbUsuarios_Gral_tbPersonas_Pers_Id");

            entity.HasOne(d => d.Role).WithMany(p => p.TbUsuarios)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbUsuarios_Acce_tbRoles_Role_Id");

            entity.HasOne(d => d.UsuaCreacionNavigation).WithMany(p => p.InverseUsuaCreacionNavigation)
                .HasForeignKey(d => d.UsuaCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbUsuarios_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.UsuaModificacionNavigation).WithMany(p => p.InverseUsuaModificacionNavigation)
                .HasForeignKey(d => d.UsuaModificacion)
                .HasConstraintName("FK_Acce_tbUsuarios_Acce_tbUsuarios_Usua_Modificacion");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}