// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Sistema_Jobster.Entities.Entities;
namespace Sistema_Jobster.DataAccess.Context;

public partial class db_ab9479_jobsterContext : DbContext
{
    public db_ab9479_jobsterContext(DbContextOptions<db_ab9479_jobsterContext> options)
        : base(options)
    {
    }

    public db_ab9479_jobsterContext()
    {
    }

    public DbSet<tbUsuarios> tbUsuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tbUsuarios>(entity =>
        {
            entity.HasKey(e => e.Usua_Id).HasName("PK_Acce_tbUsuarios_Usua_Id");

            entity.ToTable("tbUsuarios", "Acce");

            entity.Property(e => e.Usua_Contrasena).IsRequired().IsUnicode(false);
            entity.Property(e => e.Usua_Correo).IsRequired().HasMaxLength(100).IsUnicode(false);
            entity.Property(e => e.Usua_Estado).HasDefaultValue(true);
            entity.Property(e => e.Usua_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Usua_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Usua_Imagen).IsUnicode(false);
            entity.Property(e => e.Usua_Nombre).IsRequired().HasMaxLength(50).IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}