// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Sistema_Jobster.Entities.Entities;

namespace Sistema_Jobster.DataAccess.Context;

public partial class db_ab9479_jobsterContext : DbContext
{
    public db_ab9479_jobsterContext(DbContextOptions<db_ab9479_jobsterContext> options)
        : base(options)
    {
    }

    public db_ab9479_jobsterContext()
    {
    }

    public virtual DbSet<tbCargos> tbCargos { get; set; }

    public virtual DbSet<tbCategorias> tbCategorias { get; set; }

    public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }

    public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }

    public virtual DbSet<tbGuardados> tbGuardados { get; set; }

    public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }

    public virtual DbSet<tbPantallas> tbPantallas { get; set; }

    public virtual DbSet<tbPantallasPorRol> tbPantallasPorRol { get; set; }

    public virtual DbSet<tbPersonas> tbPersonas { get; set; }

    public virtual DbSet<tbPlazas> tbPlazas { get; set; }

    public virtual DbSet<tbRequisitos> tbRequisitos { get; set; }

    public virtual DbSet<tbRoles> tbRoles { get; set; }

    public virtual DbSet<tbSolicitudes> tbSolicitudes { get; set; }

    public virtual DbSet<tbTiposContrato> tbTiposContrato { get; set; }

    public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tbCargos>(entity =>
        {
            entity.HasKey(e => e.Carg_Id).HasName("PK_Plaz_tbCargos_Carg_Id");

            entity.ToTable("tbCargos", "Plaz");

            entity.Property(e => e.Carg_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Carg_Estado).HasDefaultValue(true);
            entity.Property(e => e.Carg_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Carg_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbCargosUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbCargos_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbCargosUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Plaz_tbCargos_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbCategorias>(entity =>
        {
            entity.HasKey(e => e.Cate_Id).HasName("PK_Plaz_tbCategorias_Cate_Id");

            entity.ToTable("tbCategorias", "Plaz");

            entity.Property(e => e.Cate_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Cate_Estado).HasDefaultValue(true);
            entity.Property(e => e.Cate_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Cate_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbCategoriasUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbCategorias_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbCategoriasUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Plaz_tbCategorias_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbDepartamentos>(entity =>
        {
            entity.HasKey(e => e.Depa_Codigo).HasName("PK_Gral_tbDepartamentos_Depa_Codigo");

            entity.ToTable("tbDepartamentos", "Gral");

            entity.Property(e => e.Depa_Codigo)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Depa_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Depa_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Depa_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbDepartamentosUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .HasConstraintName("FK_Gral_tbDepartamentos_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbDepartamentosUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbDepartamentos_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbEstadosCiviles>(entity =>
        {
            entity.HasKey(e => e.EsCi_Id).HasName("PK_Gral_tbEstadosCiviles_EsCi_Id");

            entity.ToTable("tbEstadosCiviles", "Gral");

            entity.Property(e => e.EsCi_Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EsCi_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.EsCi_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbEstadosCivilesUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbEstadosCiviles_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbEstadosCivilesUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbEstadosCiviles_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbGuardados>(entity =>
        {
            entity.HasKey(e => e.Guar_Id).HasName("PK_Plaz_tbGuardados_Guar_Id");

            entity.ToTable("tbGuardados", "Plaz");

            entity.Property(e => e.Guar_Estado).HasDefaultValue(true);
            entity.Property(e => e.Guar_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Guar_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Plaz).WithMany(p => p.tbGuardados)
                .HasForeignKey(d => d.Plaz_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbGuardados_Plaz_tbPlazas_Plaz_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbGuardadosUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbGuardados_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua).WithMany(p => p.tbGuardadosUsua)
                .HasForeignKey(d => d.Usua_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbGuardados_Acce_tbUsuarios_Usua_Id");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbGuardadosUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Plaz_tbGuardados_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbMunicipios>(entity =>
        {
            entity.HasKey(e => e.Muni_Codigo).HasName("PK_Gral_tbMunicipios_Muni_Codigo");

            entity.ToTable("tbMunicipios", "Gral");

            entity.Property(e => e.Muni_Codigo)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.Depa_Codigo)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Muni_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Muni_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Muni_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Depa_CodigoNavigation).WithMany(p => p.tbMunicipios)
                .HasForeignKey(d => d.Depa_Codigo)
                .HasConstraintName("FK_Gral_tbMunicipios_Gral_tbDepartamentos_Depa_Codigo");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbMunicipiosUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .HasConstraintName("FK_Gral_tbMunicipios_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbMunicipiosUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbMunicipios_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbPantallas>(entity =>
        {
            entity.HasKey(e => e.Pant_Id).HasName("PK_Acce_tbPantallas_Pant_Id");

            entity.ToTable("tbPantallas", "Acce");

            entity.Property(e => e.Pant_Controlador)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Pant_Esquema)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Pant_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Pant_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Pant_Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Pant_Ruta)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbPantallasUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .HasConstraintName("FK_Acce_tbPantallas_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbPantallasUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Acce_tbPantallas_Usua_Modificacion");
        });

        modelBuilder.Entity<tbPantallasPorRol>(entity =>
        {
            entity.HasKey(e => e.PaRo_Id).HasName("PK_Acce_tbPantallasPorRol");

            entity.ToTable("tbPantallasPorRol", "Acce");

            entity.Property(e => e.PaRo_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.PaRo_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Pant).WithMany(p => p.tbPantallasPorRol)
                .HasForeignKey(d => d.Pant_Id)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Pant_Id");

            entity.HasOne(d => d.Role).WithMany(p => p.tbPantallasPorRol)
                .HasForeignKey(d => d.Role_Id)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Role_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbPantallasPorRolUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbPantallasPorRolUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Acce_tbPantallasPorRol_Usua_Modificacion");
        });

        modelBuilder.Entity<tbPersonas>(entity =>
        {
            entity.HasKey(e => e.Pers_Id).HasName("PK_Gral_tbPersonas_Pers_Id");

            entity.ToTable("tbPersonas", "Gral");

            entity.HasIndex(e => e.Pers_DNI, "UQ__tbPerson__CC1C0A1044A96CBE").IsUnique();

            entity.Property(e => e.Muni_Codigo)
                .IsRequired()
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.Pers_Apellidos)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Pers_Curriculum).IsUnicode(false);
            entity.Property(e => e.Pers_DNI)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Pers_Direccion)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Pers_Estado).HasDefaultValue(true);
            entity.Property(e => e.Pers_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Pers_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Pers_Nombres)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Pers_Sexo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.Pers_Telefono)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.EsCi).WithMany(p => p.tbPersonas)
                .HasForeignKey(d => d.EsCi_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbPersonas_Gral_tbEstadosCiviles_EsCi_Id");

            entity.HasOne(d => d.Muni_CodigoNavigation).WithMany(p => p.tbPersonas)
                .HasForeignKey(d => d.Muni_Codigo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbPersonas_Gral_tbMunicipios_Muni_Codigo");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbPersonasUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbPersonas_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbPersonasUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Gral_tbPersonas_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbPlazas>(entity =>
        {
            entity.HasKey(e => e.Plaz_Id).HasName("PK_Plaz_tbPlazas_Plaz_Id");

            entity.ToTable("tbPlazas", "Plaz");

            entity.Property(e => e.Muni_Codigo)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.Plaz_Correo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Plaz_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Plaz_Direccion)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Plaz_Estado).HasDefaultValue(true);
            entity.Property(e => e.Plaz_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Plaz_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Plaz_Imagen)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Plaz_Informacion)
                .IsRequired()
                .HasMaxLength(4000)
                .IsUnicode(false);
            entity.Property(e => e.Plaz_Telefono)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Carg).WithMany(p => p.tbPlazas)
                .HasForeignKey(d => d.Carg_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbPlazas_Plaz_tbCargos_Carg_Id");

            entity.HasOne(d => d.Cate).WithMany(p => p.tbPlazas)
                .HasForeignKey(d => d.Cate_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbPlazas_Plaz_tbCategorias_Cate_Id");

            entity.HasOne(d => d.Muni_CodigoNavigation).WithMany(p => p.tbPlazas)
                .HasForeignKey(d => d.Muni_Codigo)
                .HasConstraintName("FK_Plaz_tbPlazas_Plaz_tbMunicipios_Muni_Codigo");

            entity.HasOne(d => d.TiCo).WithMany(p => p.tbPlazas)
                .HasForeignKey(d => d.TiCo_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbPlazas_Plaz_tbTiposContrato_TiCo_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbPlazasUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbPlazas_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua).WithMany(p => p.tbPlazasUsua)
                .HasForeignKey(d => d.Usua_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbPlazas_Acce_tbUsuarios_Usua_Id");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbPlazasUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Plaz_tbPlazas_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbRequisitos>(entity =>
        {
            entity.HasKey(e => e.Requ_Id).HasName("PK_Plaz_tbRequisitos_Requ_Id");

            entity.ToTable("tbRequisitos", "Plaz");

            entity.Property(e => e.Requ_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Requ_Estado).HasDefaultValue(true);
            entity.Property(e => e.Requ_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Requ_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Requ_Informacion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Plaz).WithMany(p => p.tbRequisitos)
                .HasForeignKey(d => d.Plaz_Id)
                .HasConstraintName("FK_Plaz_tbRequisitos_Plaz_tbPlazas_Plaz_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbRequisitosUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbRequisitos_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbRequisitosUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Plaz_tbRequisitos_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbRoles>(entity =>
        {
            entity.HasKey(e => e.Role_Id).HasName("PK_Acce_tbRoles_Role_Id");

            entity.ToTable("tbRoles", "Acce");

            entity.Property(e => e.Role_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Role_Estado).HasDefaultValue(true);
            entity.Property(e => e.Role_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Role_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbRolesUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .HasConstraintName("FK_Acce_tbRoles_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbRolesUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Acce_tbRoles_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbSolicitudes>(entity =>
        {
            entity.HasKey(e => e.Soli_Id).HasName("PK_Plaz_tbSolicitudes_Soli_Id");

            entity.ToTable("tbSolicitudes", "Plaz");

            entity.Property(e => e.Soli_Comentario)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Soli_Estado).HasDefaultValue(true);
            entity.Property(e => e.Soli_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Soli_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Soli_Revision)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.HasOne(d => d.Plaz).WithMany(p => p.tbSolicitudes)
                .HasForeignKey(d => d.Plaz_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbSolicitudes_Plaz_tbSolicitudes_Plaz_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbSolicitudesUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbSolicitudes_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua).WithMany(p => p.tbSolicitudesUsua)
                .HasForeignKey(d => d.Usua_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbSolicitudes_Acce_tbUsuarios_Usua_Id");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbSolicitudesUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Plaz_tbSolicitudes_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbTiposContrato>(entity =>
        {
            entity.HasKey(e => e.TiCo_Id).HasName("PK_Plaz_tbTiposContrato_TiCo_Id");

            entity.ToTable("tbTiposContrato", "Plaz");

            entity.Property(e => e.TiCo_Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TiCo_Estado).HasDefaultValue(true);
            entity.Property(e => e.TiCo_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.TiCo_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.tbTiposContratoUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plaz_tbTiposContrato_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.tbTiposContratoUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Plaz_tbTiposContrato_Acce_tbUsuarios_Usua_Modificacion");
        });

        modelBuilder.Entity<tbUsuarios>(entity =>
        {
            entity.HasKey(e => e.Usua_Id).HasName("PK_Acce_tbUsuarios_Usua_Id");

            entity.ToTable("tbUsuarios", "Acce");

            entity.Property(e => e.Usua_Contrasena)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Usua_Correo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Usua_Estado).HasDefaultValue(true);
            entity.Property(e => e.Usua_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Usua_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Usua_Imagen).IsUnicode(false);
            entity.Property(e => e.Usua_Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Pers).WithMany(p => p.tbUsuarios)
                .HasForeignKey(d => d.Pers_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbUsuarios_Gral_tbPersonas_Pers_Id");

            entity.HasOne(d => d.Role).WithMany(p => p.tbUsuarios)
                .HasForeignKey(d => d.Role_Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbUsuarios_Acce_tbRoles_Role_Id");

            entity.HasOne(d => d.Usua_CreacionNavigation).WithMany(p => p.InverseUsua_CreacionNavigation)
                .HasForeignKey(d => d.Usua_Creacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbUsuarios_Acce_tbUsuarios_Usua_Creacion");

            entity.HasOne(d => d.Usua_ModificacionNavigation).WithMany(p => p.InverseUsua_ModificacionNavigation)
                .HasForeignKey(d => d.Usua_Modificacion)
                .HasConstraintName("FK_Acce_tbUsuarios_Acce_tbUsuarios_Usua_Modificacion");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}